import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/footer/Footer";
import Head from 'next/document';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tyler Chenoweth",
  description: "Generated by me... duh!",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={inter.className}>
        <Navbar/>
        {/* <p>This is the layout.tsx file and were 
          importing the Navbar from /components</p> */}
        
        {children}

        <Footer/>
      </body>
    </html>
  );
}
